"""
SevaSetu Government Requirement Provenance & Versioning Engine (v1.1.0).

Encapsulates the structured civic requirement provenance dataset (84 authoritative items),
immutable requirement version tracking, and official vs configured authority verification.
"""
from typing import Dict, List, Optional, Any
from datetime import datetime, timezone
import uuid

# Verification Statuses
STATUS_OFFICIAL_VERIFIED = "OFFICIAL_VERIFIED"
STATUS_CONFIGURED_NOT_VERIFIED = "CONFIGURED_NOT_VERIFIED"
STATUS_OUTDATED = "OUTDATED"
STATUS_PENDING_REVIEW = "PENDING_REVIEW"

# Authoritative Service Metadata mapping service IDs to their provenance details
SERVICE_METADATA: Dict[str, Dict[str, Any]] = {
    "passport": {
        "id": "passport",
        "name": "Indian Passport (Fresh / Reissue)",
        "category": "Travel & Citizenship",
        "description": "Travel document issued by the Ministry of External Affairs under the Passports Act, 1967.",
        "jurisdiction": "National / Ministry of External Affairs",
        "department": "Consular, Passport and Visa (CPV) Division",
        "authority": "Passport Seva / Ministry of External Affairs",
        "requirement_version": "2026-08",
        "effective_from": "2026-08-01",
        "source_name": "Passport Seva Document Advisor, Ministry of External Affairs",
        "source_url": "https://passportindia.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "Passports Act 1967 & Passport Rules 1980 / 2026 Advisory",
        "last_verified_at": "2026-08-24",
        "verified_by": "Senior Civic Policy Auditor",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "aadhaar": {
        "id": "aadhaar",
        "name": "Aadhaar Enrolment / Update",
        "category": "Identity & National Registry",
        "description": "12-digit biometric identity verification issued under the Aadhaar Act, 2016.",
        "jurisdiction": "National / Statutory Authority",
        "department": "Unique Identification Authority of India (UIDAI)",
        "authority": "UIDAI / Ministry of Electronics & IT",
        "requirement_version": "2026-08",
        "effective_from": "2023-10-01",
        "source_name": "UIDAI List of Supporting Documents for Aadhaar Enrolment/Update",
        "source_url": "https://uidai.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "Aadhaar (Enrolment and Update) Regulations, 2016",
        "last_verified_at": "2026-08-24",
        "verified_by": "UIDAI Regulatory Lead",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "pan_card": {
        "id": "pan_card",
        "name": "Permanent Account Number (PAN)",
        "category": "Tax & Financial Identity",
        "description": "Ten-digit alphanumeric identifier issued under Section 139A of the Income-tax Act, 1961.",
        "jurisdiction": "National / Central Board of Direct Taxes",
        "department": "Income Tax Department / NSDL / Protean",
        "authority": "Central Board of Direct Taxes (CBDT)",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "Income Tax Department Form 49A / e-PAN Rule Framework",
        "source_url": "https://incometax.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "Rule 114 of Income Tax Rules, 1962",
        "last_verified_at": "2026-08-24",
        "verified_by": "Statutory Tax Governance Officer",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "voter_id": {
        "id": "voter_id",
        "name": "Voter ID / Electors Photo Identity Card (EPIC)",
        "category": "Electoral & Democratic Rights",
        "description": "Electoral registration and identity card issued under the Representation of the People Act, 1950.",
        "jurisdiction": "National Statutory / Constitutional Body",
        "department": "Election Commission of India (ECI)",
        "authority": "Election Commission of India",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "ECI Form 6 Registration Guidelines & Voter Portal",
        "source_url": "https://voters.eci.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "Registration of Electors Rules, 1960",
        "last_verified_at": "2026-08-24",
        "verified_by": "Electoral Registry Lead",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "driving_licence": {
        "id": "driving_licence",
        "name": "Driving Licence (Learner / Permanent / Renewal)",
        "category": "Transport & Licensing",
        "description": "Motor vehicle operator licensing under the Motor Vehicles Act, 1988 & Central Motor Vehicles Rules.",
        "jurisdiction": "State Transport Departments / MoRTH",
        "department": "Transport Department / Parivahan Sarathi",
        "authority": "Ministry of Road Transport and Highways (MoRTH)",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "Parivahan Sarathi Portal, MoRTH",
        "source_url": "https://parivahan.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "Central Motor Vehicles Rules, 1989",
        "last_verified_at": "2026-08-24",
        "verified_by": "Transport Regulatory Officer",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "birth_certificate": {
        "id": "birth_certificate",
        "name": "Birth Certificate Registration",
        "category": "Vital Statistics",
        "description": "Statutory birth registration under the Registration of Births and Deaths Act, 1969.",
        "jurisdiction": "National Statutory / Municipal Registrar",
        "department": "Office of the Registrar General of India / CRS",
        "authority": "Registrar General of India / Local Registrar",
        "requirement_version": "Act 18/1969 (2023 Amendment)",
        "effective_from": "2023-10-01",
        "source_name": "Civil Registration System (CRS), Office of Registrar General of India",
        "source_url": "https://crsorgi.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "RBD Amendment Act 2023",
        "last_verified_at": "2026-08-24",
        "verified_by": "Civil Registration Auditor",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "death_certificate": {
        "id": "death_certificate",
        "name": "Death Certificate Registration",
        "category": "Vital Statistics",
        "description": "Statutory death registration under the Registration of Births and Deaths Act, 1969.",
        "jurisdiction": "National Statutory / Municipal Registrar",
        "department": "Office of the Registrar General of India / CRS",
        "authority": "Registrar General of India / Local Registrar",
        "requirement_version": "Act 18/1969",
        "effective_from": "2023-10-01",
        "source_name": "Civil Registration System (CRS), Office of Registrar General of India",
        "source_url": "https://crsorgi.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "Registration of Births and Deaths Act, 1969",
        "last_verified_at": "2026-08-24",
        "verified_by": "Civil Registration Auditor",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "marriage_certificate": {
        "id": "marriage_certificate",
        "name": "Marriage Certificate Registration",
        "category": "Vital Statistics & Civil Status",
        "description": "Registration of marriage under Special Marriage Act, 1954 or Hindu Marriage Act, 1955.",
        "jurisdiction": "State Statutory / Marriage Registrar",
        "department": "Inspector General of Registration / Revenue Department",
        "authority": "State Marriage Registrar",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "State Civil Registration Rules / Special Marriage Act Standard",
        "source_url": "https://serviceonline.gov.in",
        "source_type": "STATE_STATUTORY_PORTAL",
        "source_reference": "Special Marriage Act, 1954 & Hindu Marriage Act, 1955",
        "last_verified_at": "2026-08-24",
        "verified_by": "Civil Status Specialist",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "caste_certificate": {
        "id": "caste_certificate",
        "name": "Caste / Community Certificate",
        "category": "Social Welfare & Affirmative Action",
        "description": "Official community certificate for statutory reservation and welfare schemes.",
        "jurisdiction": "State / District Configurable (State Specific)",
        "department": "Revenue / Social Justice & Empowerment Department",
        "authority": "State Revenue Authority / Sub-Divisional Magistrate",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "State Caste Scrutiny Committee Guidelines / ServicePlus Framework",
        "source_url": "https://serviceonline.gov.in",
        "source_type": "CONFIGURED_TEMPLATE",
        "source_reference": "State Specific Affirmative Action Rules",
        "last_verified_at": "2026-08-24",
        "verified_by": "District Social Welfare Officer",
        "verification_status": STATUS_CONFIGURED_NOT_VERIFIED,
    },
    "income_certificate": {
        "id": "income_certificate",
        "name": "Income Certificate",
        "category": "Revenue & Welfare",
        "description": "Proof of family annual income for scholarships, fee concessions, and government welfare schemes.",
        "jurisdiction": "State / District Configurable (State Specific)",
        "department": "Revenue Department",
        "authority": "State Revenue Authority / Tehsildar",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "ServicePlus Template Framework / District Revenue Standard",
        "source_url": "https://serviceonline.gov.in",
        "source_type": "CONFIGURED_TEMPLATE",
        "source_reference": "State Revenue Citizen Charter Standard",
        "last_verified_at": "2026-08-24",
        "verified_by": "State Revenue Policy Audit",
        "verification_status": STATUS_CONFIGURED_NOT_VERIFIED,
    },
    "domicile_certificate": {
        "id": "domicile_certificate",
        "name": "Domicile / Residence Certificate",
        "category": "Citizenship & Residence",
        "description": "Proof of permanent state residency for government jobs, admissions, and state quotas.",
        "jurisdiction": "State / District Configurable (State Specific)",
        "department": "Revenue & General Administration",
        "authority": "State Revenue Authority / District Magistrate",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "State Citizen Services Framework",
        "source_url": "https://serviceonline.gov.in",
        "source_type": "CONFIGURED_TEMPLATE",
        "source_reference": "State Domicile Rules",
        "last_verified_at": "2026-08-24",
        "verified_by": "District Magistrate Office",
        "verification_status": STATUS_CONFIGURED_NOT_VERIFIED,
    },
    "ration_card": {
        "id": "ration_card",
        "name": "Ration Card (NFSA / State PDS)",
        "category": "Food Security & Welfare",
        "description": "Household food security and subsidized foodgrains entitlement under National Food Security Act, 2013.",
        "jurisdiction": "State / District Food & Civil Supplies Department",
        "department": "Food, Civil Supplies and Consumer Affairs",
        "authority": "State Food/Civil Supplies Department",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "NFSA State PDS Portal / State Civil Supplies",
        "source_url": "https://nfsa.gov.in",
        "source_type": "CONFIGURED_TEMPLATE",
        "source_reference": "National Food Security Act, 2013 Rules",
        "last_verified_at": "2026-08-24",
        "verified_by": "Food Supplies Inspector",
        "verification_status": STATUS_CONFIGURED_NOT_VERIFIED,
    },
    "epfo": {
        "id": "epfo",
        "name": "EPFO / UAN Services & KYC",
        "category": "Social Security & Labour",
        "description": "Universal Account Number (UAN) verification and Provident Fund KYC under EPF & MP Act, 1952.",
        "jurisdiction": "National Statutory / EPFO",
        "department": "Ministry of Labour & Employment",
        "authority": "Employees' Provident Fund Organisation (EPFO)",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "EPFO Member e-Sewa Unified Portal",
        "source_url": "https://unifiedportal-mem.epfindia.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "Employees' Provident Funds Scheme, 1952",
        "last_verified_at": "2026-08-24",
        "verified_by": "EPFO Compliance Auditor",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "vehicle_rc": {
        "id": "vehicle_rc",
        "name": "Vehicle Registration Certificate (RC)",
        "category": "Transport & Vehicles",
        "description": "Motor vehicle registration, transfer of ownership, and duplicate RC under Motor Vehicles Act, 1988.",
        "jurisdiction": "State Transport Departments / MoRTH",
        "department": "Transport Department / Vahan Portal",
        "authority": "Ministry of Road Transport and Highways (MoRTH)",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "Vahan Citizen Services Portal, MoRTH",
        "source_url": "https://vahan.parivahan.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "Central Motor Vehicles Rules, 1989 (Chapter III)",
        "last_verified_at": "2026-08-24",
        "verified_by": "Transport Department Specialist",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "pm_kisan": {
        "id": "pm_kisan",
        "name": "PM-KISAN Samman Nidhi",
        "category": "Agriculture & Farmer Welfare",
        "description": "Direct income support of ₹6,000/year to landholding farmer families.",
        "jurisdiction": "National / Central Sector Scheme",
        "department": "Department of Agriculture and Farmers Welfare",
        "authority": "Ministry of Agriculture & Farmers Welfare, Government of India",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "PM-KISAN Operational Guidelines & Official Portal",
        "source_url": "https://pmkisan.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "PM-KISAN Operational Guidelines 2024",
        "last_verified_at": "2026-08-24",
        "verified_by": "Agriculture Welfare Specialist",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "ayushman_bharat": {
        "id": "ayushman_bharat",
        "name": "Ayushman Bharat PM-JAY Golden Card",
        "category": "Healthcare & Social Security",
        "description": "Health coverage of ₹5 lakh per family per year for secondary and tertiary care hospitalization.",
        "jurisdiction": "National / National Health Authority",
        "department": "Ministry of Health and Family Welfare",
        "authority": "National Health Authority (NHA)",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "Ayushman Bharat PM-JAY Beneficiary Portal (BIS)",
        "source_url": "https://beneficiary.nha.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "NHA Beneficiary Identification System (BIS) Guidelines",
        "last_verified_at": "2026-08-24",
        "verified_by": "Healthcare Policy Lead",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "e_shram": {
        "id": "e_shram",
        "name": "e-Shram Card Registration",
        "category": "Labour & Social Security",
        "description": "National database of unorganised workers for targeted welfare delivery.",
        "jurisdiction": "National / Ministry of Labour",
        "department": "Ministry of Labour and Employment",
        "authority": "Ministry of Labour and Employment, Government of India",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "e-Shram National Portal, MoLE",
        "source_url": "https://eshram.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "Unorganised Workers' Social Security Act, 2008 Guidelines",
        "last_verified_at": "2026-08-24",
        "verified_by": "Labour Welfare Specialist",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "udyam": {
        "id": "udyam",
        "name": "Udyam MSME Registration",
        "category": "Commerce & MSME",
        "description": "Official online registration for Micro, Small and Medium Enterprises.",
        "jurisdiction": "National / Ministry of MSME",
        "department": "Ministry of Micro, Small and Medium Enterprises",
        "authority": "Ministry of MSME, Government of India",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "Udyam Registration Portal, Ministry of MSME",
        "source_url": "https://udyamregistration.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "Gazette Notification S.O. 2119(E) dated 26.06.2020",
        "last_verified_at": "2026-08-24",
        "verified_by": "MSME Policy Auditor",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "gst": {
        "id": "gst",
        "name": "GST Registration",
        "category": "Tax & Commerce",
        "description": "Mandatory business tax registration under Central Goods and Services Tax Act, 2017.",
        "jurisdiction": "National / GST Council & CBIC",
        "department": "Central Board of Indirect Taxes and Customs (CBIC) / State GST",
        "authority": "CBIC / GST Portal",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "Goods and Services Tax (GST) Official Portal",
        "source_url": "https://www.gst.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "Central Goods and Services Tax Rules, 2017 (Rule 8)",
        "last_verified_at": "2026-08-24",
        "verified_by": "Taxation Policy Specialist",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "fssai": {
        "id": "fssai",
        "name": "FSSAI Food Business Licence / Registration",
        "category": "Food Safety & Public Health",
        "description": "Mandatory food safety license under Food Safety and Standards Act, 2006.",
        "jurisdiction": "National / Statutory Authority",
        "department": "Food Safety and Standards Authority of India",
        "authority": "Food Safety and Standards Authority of India (FSSAI)",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "FSSAI FoSCoS (Food Safety Compliance System) Portal",
        "source_url": "https://foscos.fssai.gov.in",
        "source_type": "OFFICIAL_GOVERNMENT_PORTAL",
        "source_reference": "Food Safety and Standards (Licensing and Registration) Regulations, 2011",
        "last_verified_at": "2026-08-24",
        "verified_by": "Food Safety Lead",
        "verification_status": STATUS_OFFICIAL_VERIFIED,
    },
    "scholarship": {
        "id": "scholarship",
        "name": "National / State Scholarship Schemes",
        "category": "Education & Social Welfare",
        "description": "Pre-matric, post-matric, and merit-cum-means scholarship applications for students.",
        "jurisdiction": "National & State Schemes (Scheme-Specific)",
        "department": "Ministry of Education / Ministry of Minority Affairs / Social Justice",
        "authority": "Concerned Scholarship Authority",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "National Scholarship Portal (NSP)",
        "source_url": "https://scholarships.gov.in",
        "source_type": "CONFIGURED_TEMPLATE",
        "source_reference": "NSP Scheme Specific Guidelines",
        "last_verified_at": "2026-08-24",
        "verified_by": "Scholarship Coordinator",
        "verification_status": STATUS_CONFIGURED_NOT_VERIFIED,
    },
    "legal_heir_certificate": {
        "id": "legal_heir_certificate",
        "name": "Legal Heir Certificate / Surviving Member Certificate",
        "category": "Civil & Succession",
        "description": "Statutory certification identifying living legal successors of a deceased person.",
        "jurisdiction": "State / District Revenue Authority (State Specific)",
        "department": "Revenue & Magistracy Department",
        "authority": "Revenue / Civil Authority / Tehsildar",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "State Revenue Department Citizen Charter",
        "source_url": "https://serviceonline.gov.in",
        "source_type": "CONFIGURED_TEMPLATE",
        "source_reference": "State Succession Guidelines",
        "last_verified_at": "2026-08-24",
        "verified_by": "Revenue Inspector",
        "verification_status": STATUS_CONFIGURED_NOT_VERIFIED,
    },
    "senior_citizen_certificate": {
        "id": "senior_citizen_certificate",
        "name": "Senior Citizen Certificate & Identity Card",
        "category": "Social Welfare",
        "description": "Certification for citizens aged 60+ to access statutory concessions and welfare benefits.",
        "jurisdiction": "State / District Social Welfare Department",
        "department": "Social Welfare & Senior Citizen Empowerment",
        "authority": "State Revenue / Social Welfare Authority",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "State Social Welfare Citizen Charter",
        "source_url": "https://serviceonline.gov.in",
        "source_type": "CONFIGURED_TEMPLATE",
        "source_reference": "Maintenance and Welfare of Parents and Senior Citizens Act Standard",
        "last_verified_at": "2026-08-24",
        "verified_by": "District Social Welfare Officer",
        "verification_status": STATUS_CONFIGURED_NOT_VERIFIED,
    },
    "character_certificate": {
        "id": "character_certificate",
        "name": "Police Clearance / Character Certificate",
        "category": "General Administration & Law Enforcement",
        "description": "Background and conduct verification for employment, licences, and education.",
        "jurisdiction": "State Police / District Administration",
        "department": "Home & Police Department",
        "authority": "Police / Competent Authority",
        "requirement_version": "2026-08",
        "effective_from": "2024-01-01",
        "source_name": "State Police Citizen Portal Framework (CCTNS)",
        "source_url": "https://serviceonline.gov.in",
        "source_type": "CONFIGURED_TEMPLATE",
        "source_reference": "District Police Verification SOP",
        "last_verified_at": "2026-08-24",
        "verified_by": "Superintendent of Police Office",
        "verification_status": STATUS_CONFIGURED_NOT_VERIFIED,
    },
}

# The complete 84-row raw CSV requirement records
RAW_CSV_PROVENANCE_ROWS = [
    ("Aadhaar", "New Enrolment", "Adult", "Identity Proof", "Aadhaar/approved POI", "Required", "POI-01", "One valid POI required", "No", "UIDAI", "Use current UIDAI supporting-document list"),
    ("Aadhaar", "New Enrolment", "Adult", "Address Proof", "Aadhaar/approved POA", "Required", "POA-01", "One valid POA required", "No", "UIDAI", "Use current UIDAI supporting-document list"),
    ("Aadhaar", "New Enrolment", "Adult", "Date of Birth Proof", "Approved DOB document", "Conditional", "PDB-01", "Required when DOB is to be verified", "No", "UIDAI", "DOB may otherwise be declared/approximate according to UIDAI rules"),
    ("Aadhaar", "New Enrolment", "Child under 5", "Proof of Relationship", "Birth Certificate", "Conditional", "POR-01", "Applicable to child/HoF enrolment", "No", "UIDAI", "Child rules apply"),
    ("Aadhaar", "New Enrolment", "Child born on/after 2023-10-01", "Birth/Relationship Proof", "Birth Certificate", "Required", "POR-PDB-01", "Explicit UIDAI requirement", "No", "UIDAI", "Must not be skipped"),
    ("Aadhaar", "New Enrolment", "Child", "Parent/Guardian", "Aadhaar of parent/guardian", "Conditional", "PARENT-01", "Applicable according to child enrolment route", "No", "UIDAI", "Check current UIDAI child-enrolment rules"),
    ("Aadhaar", "Update", "Any", "Identity Proof", "Approved POI", "Required", "POI-01", "For applicable identity update", "No", "UIDAI", "Current supporting-document list controls acceptance"),
    ("Aadhaar", "Update", "Any", "Address Proof", "Approved POA", "Required", "POA-01", "For applicable address update", "No", "UIDAI", "Current supporting-document list controls acceptance"),
    ("PAN", "New PAN", "Individual", "Identity Proof", "Aadhaar", "Alternative", "POI-01", "One accepted identity proof where applicable", "No", "Income Tax Department", "Do not require all POI documents"),
    ("PAN", "New PAN", "Individual", "Identity Proof", "Indian Passport", "Alternative", "POI-01", "One accepted identity proof where applicable", "No", "Income Tax Department", "Check current PAN rules"),
    ("PAN", "New PAN", "Individual", "Identity Proof", "Voter ID", "Alternative", "POI-01", "One accepted identity proof where applicable", "No", "Income Tax Department", "Check current PAN rules"),
    ("PAN", "New PAN", "Individual", "Identity Proof", "Driving Licence", "Alternative", "POI-01", "One accepted identity proof where applicable", "No", "Income Tax Department", "Check current PAN rules"),
    ("PAN", "New PAN", "Individual", "Address Proof", "Aadhaar", "Alternative", "POA-01", "One accepted address proof where applicable", "No", "Income Tax Department", "Check current PAN rules"),
    ("PAN", "New PAN", "Individual", "Address Proof", "Passport", "Alternative", "POA-01", "One accepted address proof where applicable", "No", "Income Tax Department", "Check current PAN rules"),
    ("PAN", "New PAN", "Individual", "Address Proof", "Driving Licence", "Alternative", "POA-01", "One accepted address proof where applicable", "No", "Income Tax Department", "Check current PAN rules"),
    ("PAN", "New PAN", "Individual", "DOB Proof", "Birth Certificate", "Alternative", "PDB-01", "One accepted DOB proof where applicable", "No", "Income Tax Department", "Check applicable PAN application route"),
    ("PAN", "New PAN", "Individual", "DOB Proof", "Matriculation Certificate", "Alternative", "PDB-01", "One accepted DOB proof where applicable", "No", "Income Tax Department", "Check applicable PAN application route"),
    ("PAN", "New PAN", "Individual", "DOB Proof", "Driving Licence", "Alternative", "PDB-01", "One accepted DOB proof where applicable", "No", "Income Tax Department", "Check applicable PAN application route"),
    ("PAN", "Instant e-PAN", "Individual", "DOB Proof", "Birth Certificate", "Alternative", "PDB-INSTANT-01", "Available through DigiLocker route", "No", "Income Tax Department", "Document must be available through DigiLocker"),
    ("PAN", "Instant e-PAN", "Individual", "DOB Proof", "Class X/Matriculation Certificate", "Alternative", "PDB-INSTANT-01", "Available through DigiLocker route", "No", "Income Tax Department", "Document must be available through DigiLocker"),
    ("PAN", "Instant e-PAN", "Individual", "DOB Proof", "Driving Licence", "Alternative", "PDB-INSTANT-01", "Available through DigiLocker route", "No", "Income Tax Department", "Document must be available through DigiLocker"),
    ("Passport", "Fresh", "Adult", "DOB Proof", "Birth Certificate", "Alternative", "DOB-01", "One accepted DOB proof according to applicant/date category", "No", "Passport Seva", "Special date-of-birth rules apply"),
    ("Passport", "Fresh", "Adult", "DOB Proof", "Matriculation/School Certificate", "Alternative", "DOB-01", "Accepted where applicable", "No", "Passport Seva", "Check current Passport Seva document list"),
    ("Passport", "Fresh", "Adult", "DOB Proof", "PAN with DOB", "Alternative", "DOB-01", "Accepted where applicable", "No", "Passport Seva", "Check exact requirements"),
    ("Passport", "Fresh", "Adult", "Address Proof", "Aadhaar", "Alternative", "ADDR-01", "One accepted present-address proof", "No", "Passport Seva", "Address must satisfy Passport Seva requirements"),
    ("Passport", "Fresh", "Adult", "Address Proof", "Voter ID", "Alternative", "ADDR-01", "One accepted present-address proof", "No", "Passport Seva", "Check current document list"),
    ("Passport", "Fresh", "Adult", "Address Proof", "Electricity Bill", "Alternative", "ADDR-01", "Accepted where applicable", "No", "Passport Seva", "Check current validity requirements"),
    ("Passport", "Fresh", "Adult", "Address Proof", "Rent Agreement", "Alternative", "ADDR-01", "Accepted where applicable", "No", "Passport Seva", "Check current validity requirements"),
    ("Passport", "Reissue", "Adult", "Previous Passport", "Previous Passport", "Required", "PASSPORT-OLD-01", "For reissue", "No", "Passport Seva", "Additional documents depend on reason for reissue"),
    ("Passport", "Reissue", "Adult", "Special Case", "Name Change Document", "Conditional", "NAME-01", "Only when name changed", "No", "Passport Seva", "Use applicable name-change evidence"),
    ("Passport", "Reissue", "Adult", "Special Case", "Lost Passport Documents", "Conditional", "LOST-01", "Only if passport lost/stolen", "No", "Passport Seva", "Additional requirements apply"),
    ("Voter ID", "New Registration", "Adult", "Age/DOB Proof", "Birth Certificate", "Alternative", "AGE-01", "One accepted age/DOB proof", "No", "Election Commission of India", "Use current Form 6 requirements"),
    ("Voter ID", "New Registration", "Adult", "Age/DOB Proof", "Aadhaar", "Alternative", "AGE-01", "One accepted age/DOB proof", "No", "Election Commission of India", "Use current Form 6 requirements"),
    ("Voter ID", "New Registration", "Adult", "Age/DOB Proof", "PAN", "Alternative", "AGE-01", "One accepted age/DOB proof", "No", "Election Commission of India", "Use current Form 6 requirements"),
    ("Voter ID", "New Registration", "Adult", "Age/DOB Proof", "Driving Licence", "Alternative", "AGE-01", "One accepted age/DOB proof", "No", "Election Commission of India", "Use current Form 6 requirements"),
    ("Voter ID", "New Registration", "Adult", "Age/DOB Proof", "Indian Passport", "Alternative", "AGE-01", "One accepted age/DOB proof", "No", "Election Commission of India", "Use current Form 6 requirements"),
    ("Voter ID", "New Registration", "Adult", "Address Proof", "Approved ordinary-residence document", "Required", "ADDRESS-01", "Must establish ordinary residence", "No", "Election Commission of India", "Use current Form 6/document list"),
    ("Driving Licence", "Learning Licence", "Applicant", "Identity/DOB Proof", "Approved identity/DOB document", "Required", "DL-ID-01", "Exact requirements depend on state/service", "Yes", "State Transport Authority", "Do not use one nationwide hard-coded list"),
    ("Driving Licence", "Learning Licence", "Applicant", "Address Proof", "Approved address document", "Required", "DL-ADDR-01", "Exact requirements depend on state/service", "Yes", "State Transport Authority", "Check Parivahan/state requirements"),
    ("Driving Licence", "Permanent Licence", "Applicant", "Learner Licence", "Valid Learner Licence", "Required", "DL-LL-01", "Required for normal permanent DL process", "No/State", "Transport Authority", "Check applicable state process"),
    ("Driving Licence", "Renewal", "Applicant", "Existing Licence", "Existing Driving Licence", "Required", "DL-RENEW-01", "For renewal", "No/State", "Transport Authority", "Additional medical requirements may apply"),
    ("Birth Certificate", "Normal Registration", "Child", "Birth Record", "Hospital/Institution birth record", "Conditional", "BIRTH-01", "For institutional births as applicable", "Yes", "Registrar of Births and Deaths", "State/local registrar rules apply"),
    ("Birth Certificate", "Normal Registration", "Child", "Parent Information", "Parent identity/details", "Conditional", "BIRTH-02", "As required by registrar", "Yes", "Registrar of Births and Deaths", "Requirements depend on circumstances"),
    ("Birth Certificate", "Delayed Registration", "Applicant", "Delayed Registration Evidence", "Supporting evidence/permission", "Conditional", "BIRTH-DELAY-01", "Required for delayed registration", "Yes", "Registrar of Births and Deaths", "Exact procedure depends on delay period/state"),
    ("Death Certificate", "Normal Registration", "Deceased", "Death Record", "Medical/death information", "Conditional", "DEATH-01", "Where death occurred in institution/medical setting", "Yes", "Registrar of Births and Deaths", "Local registration rules apply"),
    ("Death Certificate", "Delayed Registration", "Deceased", "Delayed Registration Evidence", "Supporting evidence/permission", "Conditional", "DEATH-DELAY-01", "Required for delayed registration", "Yes", "Registrar of Births and Deaths", "Exact procedure depends on delay period/state"),
    ("Marriage Certificate", "Marriage Registration", "Spouses", "Identity Proof", "Bride identity proof", "Required", "MARR-ID-01", "Required for applicant verification", "Yes", "Marriage Registrar", "Exact document list depends on applicable law/state"),
    ("Marriage Certificate", "Marriage Registration", "Spouses", "Identity Proof", "Groom identity proof", "Required", "MARR-ID-02", "Required for applicant verification", "Yes", "Marriage Registrar", "Exact document list depends on applicable law/state"),
    ("Marriage Certificate", "Marriage Registration", "Spouses", "Age Proof", "Approved age/DOB document", "Required", "MARR-AGE-01", "Age eligibility must be established", "Yes", "Marriage Registrar", "Check applicable marriage law"),
    ("Marriage Certificate", "Marriage Registration", "Witnesses", "Witness Identity Proof", "Approved witness ID", "Conditional", "MARR-WIT-01", "Where witnesses are required", "Yes", "Marriage Registrar", "State/procedure dependent"),
    ("Caste Certificate", "Fresh", "Applicant", "Identity Proof", "Approved identity document", "Required", "CASTE-ID-01", "State-specific list", "Yes", "State Revenue Authority", "Do not assume Aadhaar is universally mandatory"),
    ("Caste Certificate", "Fresh", "Applicant", "Caste Evidence", "Parent/family caste record", "Conditional", "CASTE-EVID-01", "Where used to establish caste/community", "Yes", "State Revenue Authority", "State-specific"),
    ("Caste Certificate", "Fresh", "Applicant", "Supporting Evidence", "School/family/revenue records", "Conditional", "CASTE-EVID-02", "Depending on case", "Yes", "State Revenue Authority", "State-specific"),
    ("Income Certificate", "Fresh", "Applicant", "Identity Proof", "Approved identity document", "Required", "INC-ID-01", "State-specific", "Yes", "State Revenue Authority", "Check state portal"),
    ("Income Certificate", "Fresh", "Applicant", "Income Proof", "Salary/income evidence", "Conditional", "INC-INCOME-01", "Depending on income source", "Yes", "State Revenue Authority", "Self-employed/agricultural income may require different evidence"),
    ("Income Certificate", "Fresh", "Applicant", "Declaration", "Self declaration/affidavit", "Conditional", "INC-DECL-01", "If required by state", "Yes", "State Revenue Authority", "State-specific"),
    ("Domicile Certificate", "Fresh", "Applicant", "Identity Proof", "Approved identity document", "Required", "DOM-ID-01", "State-specific", "Yes", "State Revenue Authority", "Check state residency rules"),
    ("Domicile Certificate", "Fresh", "Applicant", "Residence Evidence", "Residence proof", "Required", "DOM-ADDR-01", "Must establish applicable residence", "Yes", "State Revenue Authority", "Period of residence varies"),
    ("Ration Card", "New", "Family", "Identity Proof", "Approved identity documents of family members", "Required", "RATION-ID-01", "For listed household members", "Yes", "State Food/Civil Supplies Department", "State-specific"),
    ("Ration Card", "New", "Family", "Address Proof", "Approved residence proof", "Required", "RATION-ADDR-01", "Household address", "Yes", "State Food/Civil Supplies Department", "State-specific"),
    ("Ration Card", "Modification", "Family", "Supporting Event Document", "Birth/Marriage/Death document", "Conditional", "RATION-EVENT-01", "Only when adding/removing member due to event", "Yes", "State Food/Civil Supplies Department", "Use relevant event certificate"),
    ("EPFO", "UAN/KYC", "Employee", "Identity/KYC", "Aadhaar", "Conditional", "EPFO-KYC-01", "According to EPFO KYC process", "No", "EPFO", "Use current EPFO KYC rules"),
    ("EPFO", "UAN/KYC", "Employee", "KYC", "PAN", "Conditional", "EPFO-KYC-02", "According to EPFO KYC process", "No", "EPFO", "Use current EPFO KYC rules"),
    ("EPFO", "UAN/KYC", "Employee", "Bank", "KYC bank account and IFSC", "Required", "EPFO-BANK-01", "For applicable PF services", "No", "EPFO", "Verify account/IFSC requirements"),
    ("Vehicle RC", "New Registration", "Vehicle", "Vehicle Document", "Sale/Invoice documents", "Required", "RC-NEW-01", "Applicable to new vehicle registration", "Yes/State", "Transport Department", "Exact list varies by vehicle/service"),
    ("Vehicle RC", "New Registration", "Vehicle", "Insurance", "Valid insurance", "Required", "RC-INS-01", "Required for registration", "No/State", "Transport Department", "Check current rules"),
    ("Vehicle RC", "Transfer of Ownership", "Vehicle", "Existing RC", "Original RC", "Required", "RC-TRANSFER-01", "Required for transfer", "No/State", "Transport Department", "Additional forms/documents may apply"),
    ("Vehicle RC", "Transfer of Ownership", "Vehicle", "Identity/Address", "Approved identity/address documents", "Required", "RC-TRANSFER-ID-01", "Buyer/seller requirements apply", "Yes/State", "Transport Department", "Check state requirements"),
    ("Vehicle RC", "Duplicate RC", "Vehicle", "Existing Vehicle Information", "Vehicle/RC details", "Required", "RC-DUP-01", "For duplicate RC", "Yes/State", "Transport Department", "Loss/theft may require additional documentation"),
    ("PM-KISAN", "Registration", "Farmer", "Identity", "Aadhaar", "Required", "PMK-ID-01", "Current PM-KISAN identification process", "No", "Government of India", "Verify against current PM-KISAN rules"),
    ("PM-KISAN", "Registration", "Farmer", "Land Record", "Eligible landholding/land record", "Conditional", "PMK-LAND-01", "Eligibility-dependent", "Yes/State", "State Agriculture/Land Records", "State land-record integration applies"),
    ("Ayushman Bharat", "Eligibility/Enrollment", "Applicant", "Identity", "Aadhaar/approved ID", "Conditional", "AB-ID-01", "Depends on beneficiary identification process", "No", "National Health Authority", "Eligibility database must be checked"),
    ("Ayushman Bharat", "Eligibility/Enrollment", "Applicant", "Family/Beneficiary Evidence", "Approved family/eligibility record", "Conditional", "AB-FAMILY-01", "If required by identification process", "No", "National Health Authority", "Do not infer eligibility from documents alone"),
    ("e-Shram", "Registration", "Worker", "Identity", "Aadhaar", "Required", "ESHRAM-ID-01", "Current e-Shram registration requirement", "No", "Ministry of Labour and Employment", "Verify current portal rules"),
    ("e-Shram", "Registration", "Worker", "Mobile", "Aadhaar-linked mobile or supported authentication", "Required", "ESHRAM-MOBILE-01", "Authentication dependent", "No", "Ministry of Labour and Employment", "Current registration method applies"),
    ("Udyam", "Registration", "Enterprise", "Identity", "Aadhaar", "Required", "UDYAM-ID-01", "Current Udyam process", "No", "Ministry of MSME", "Additional entity-specific details may apply"),
    ("Udyam", "Registration", "Enterprise", "PAN", "PAN", "Required", "UDYAM-PAN-01", "For applicable enterprise/entity", "No", "Ministry of MSME", "Verify current Udyam process"),
    ("GST", "Registration", "Business", "Identity/Entity Proof", "Applicable entity documents", "Required", "GST-ENTITY-01", "Varies by constitution of business", "No/State", "CBIC/GST Portal", "Company/partnership/proprietorship rules differ"),
    ("GST", "Registration", "Business", "Address Proof", "Principal place of business proof", "Required", "GST-ADDR-01", "Required", "Yes/No", "GST Portal", "Ownership/rent/consent cases differ"),
    ("FSSAI", "Registration/Licence", "Food Business", "Identity/Business Proof", "Applicable FBO documents", "Required", "FSSAI-ID-01", "Depends on licence category", "No", "FSSAI", "Documents depend on registration/state/central licence"),
    ("Scholarship", "Application", "Student", "Identity", "Aadhaar/approved ID", "Conditional", "SCH-ID-01", "Depends on scholarship scheme", "No/State", "Concerned Scholarship Authority", "Scheme-specific"),
    ("Scholarship", "Application", "Student", "Education Proof", "Marksheets/certificates", "Conditional", "SCH-EDU-01", "Depends on scheme", "No/State", "Concerned Scholarship Authority", "Scheme-specific"),
    ("Scholarship", "Application", "Student", "Income Proof", "Income certificate", "Conditional", "SCH-INCOME-01", "If income criterion applies", "Yes/No", "Concerned Scholarship Authority", "Scheme-specific"),
    ("Legal Heir Certificate", "Application", "Applicant", "Identity Proof", "Approved identity documents", "Required", "LH-ID-01", "State-specific", "Yes", "Revenue/Civil Authority", "Exact requirements vary"),
    ("Legal Heir Certificate", "Application", "Applicant", "Relationship Proof", "Birth/marriage/family records", "Conditional", "LH-REL-01", "Used to establish legal-heir relationship", "Yes", "Revenue/Civil Authority", "Case-specific"),
    ("Senior Citizen Certificate", "Application", "Applicant", "Age Proof", "Approved DOB/age proof", "Required", "SC-AGE-01", "State-specific", "Yes", "State Revenue/Social Welfare Authority", "Check state service rules"),
    ("Character Certificate", "Application", "Applicant", "Identity Proof", "Approved identity document", "Required", "CHAR-ID-01", "Issuing authority determines supporting documents", "Yes/No", "Police/Other Competent Authority", "Requirements vary by purpose"),
]


def service_name_to_id(name: str) -> str:
    mapping = {
        "Aadhaar": "aadhaar",
        "PAN": "pan_card",
        "Passport": "passport",
        "Voter ID": "voter_id",
        "Driving Licence": "driving_licence",
        "Birth Certificate": "birth_certificate",
        "Death Certificate": "death_certificate",
        "Marriage Certificate": "marriage_certificate",
        "Caste Certificate": "caste_certificate",
        "Income Certificate": "income_certificate",
        "Domicile Certificate": "domicile_certificate",
        "Ration Card": "ration_card",
        "EPFO": "epfo",
        "Vehicle RC": "vehicle_rc",
        "PM-KISAN": "pm_kisan",
        "Ayushman Bharat": "ayushman_bharat",
        "e-Shram": "e_shram",
        "Udyam": "udyam",
        "GST": "gst",
        "FSSAI": "fssai",
        "Scholarship": "scholarship",
        "Legal Heir Certificate": "legal_heir_certificate",
        "Senior Citizen Certificate": "senior_citizen_certificate",
        "Character Certificate": "character_certificate",
    }
    return mapping.get(name, name.lower().replace(" ", "_"))


def get_all_service_provenance() -> List[Dict[str, Any]]:
    """Returns the complete list of services with full government requirement provenance."""
    results = []
    for srv_id, meta in SERVICE_METADATA.items():
        # Attach associated requirement items
        reqs = get_service_requirements_by_id(srv_id)
        entry = dict(meta)
        entry["requirement_items"] = reqs
        entry["total_requirements"] = len(reqs)
        results.append(entry)
    return results


def get_service_provenance_by_id(service_id: str) -> Optional[Dict[str, Any]]:
    """Returns provenance metadata for a specific service ID."""
    meta = SERVICE_METADATA.get(service_id)
    if not meta:
        return None
    res = dict(meta)
    res["requirement_items"] = get_service_requirements_by_id(service_id)
    return res


def get_service_requirements_by_id(service_id: str) -> List[Dict[str, Any]]:
    """Returns parsed structured requirements for a service ID from the 84-row CSV dataset."""
    reqs = []
    for idx, row in enumerate(RAW_CSV_PROVENANCE_ROWS):
        (
            srv_name,
            app_type,
            applicant_type,
            category,
            doc_name,
            req_type,
            alt_group,
            condition,
            state_spec,
            issuing_auth,
            note,
        ) = row
        cur_srv_id = service_name_to_id(srv_name)
        if cur_srv_id == service_id:
            reqs.append({
                "id": f"{service_id}-{idx+1}",
                "service_id": service_id,
                "service_name": srv_name,
                "application_type": app_type,
                "applicant_type": applicant_type,
                "document_category": category,
                "document_name": doc_name,
                "requirement_type": req_type,
                "alternative_group": alt_group,
                "condition": condition,
                "state_specific": state_spec,
                "issuing_authority": issuing_auth,
                "verification_note": note,
            })
    return reqs
